// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a388a4e8c1271596 "Pat's", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Hover' | 'Tablet - Primary' | 'Tablet - Hovered' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-LKSUI2VU.js";

// virtual:folder-new
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8Whuce2ANLDhAOylWVwh/w9kzmftgfg2xBxdjWToZ/sHFFwTk7_.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/39Ohi90x9XWqhtvgqBD8/V8mC30fOnihJdIu0X9Zu/APT599laW.js
import { fontStore } from "unframer";
fontStore.loadFonts(["GF;Instrument Sans-500", "GF;Instrument Sans-500italic"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentsans/v3/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npST3-QfwmS0v3_7Y.woff2",
				weight: "500",
			},
			{
				family: "Instrument Sans",
				openType: true,
				source: "google",
				style: "italic",
				url: "https://fonts.gstatic.com/s/instrumentsans/v3/pxigypc9vsFDm051Uf6KVwgkfoSbSnNPooZAN0lInHGpCWNE27lgU-XJojENut22kywN2u7YUwU.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	`.framer-zbKUM .framer-styles-preset-8kwqzc:not(.rich-text-wrapper), .framer-zbKUM .framer-styles-preset-8kwqzc.rich-text-wrapper h2 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-zbKUM .framer-styles-preset-8kwqzc:not(.rich-text-wrapper), .framer-zbKUM .framer-styles-preset-8kwqzc.rich-text-wrapper h2 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-zbKUM .framer-styles-preset-8kwqzc:not(.rich-text-wrapper), .framer-zbKUM .framer-styles-preset-8kwqzc.rich-text-wrapper h2 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 28px; --framer-font-style: normal; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className = "framer-zbKUM";

// /:https://framerusercontent.com/modules/gNPJfpW4Z2xrrN0y7u6v/q2HDNouQs2U08zOhhx8w/cKcUkx2tM.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"GF;Instrument Sans-500",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentsans/v1/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npST3-QfwmS0v3_7Y.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/vFzuJY0c65av44uhEKB6vyjFMg.woff2",
				weight: "400",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	`.framer-vxv2P .framer-styles-preset-1o5tu90:not(.rich-text-wrapper), .framer-vxv2P .framer-styles-preset-1o5tu90.rich-text-wrapper p { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 24px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-vxv2P .framer-styles-preset-1o5tu90:not(.rich-text-wrapper), .framer-vxv2P .framer-styles-preset-1o5tu90.rich-text-wrapper p { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 22px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-vxv2P .framer-styles-preset-1o5tu90:not(.rich-text-wrapper), .framer-vxv2P .framer-styles-preset-1o5tu90.rich-text-wrapper p { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 20px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.03em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className2 = "framer-vxv2P";

// /:https://framerusercontent.com/modules/xjj2Y71HBI0ye3im2EPu/WOPDFvV9P9WirCuKeBa6/xOozWzlxf.js
import { fontStore as fontStore3 } from "unframer";
fontStore3.loadFonts([
	"GF;Instrument Sans-500",
	"Inter-Black",
	"Inter-BlackItalic",
	"Inter-BoldItalic",
]);
var fonts3 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Instrument Sans",
				openType: true,
				source: "google",
				style: "normal",
				url: "https://fonts.gstatic.com/s/instrumentsans/v3/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npST3-QfwmS0v3_7Y.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/mkY5Sgyq51ik0AMrSBwhm9DJg.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/X5hj6qzcHUYv7h1390c8Rhm6550.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/gQhNpS3tN86g8RcVKYUUaKt2oMQ.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cugnVhSraaRyANCaUtI5FV17wk.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/5HcVoGak8k5agFJSaKa4floXVu0.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/jn4BtSPLlS0NDp1KiFAtFKiiY0o.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/P2Bw01CtL0b9wqygO0sSVogWbo.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/05KsVHGDmqXSBXM4yRZ65P8i0s.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/ky8ovPukK4dJ1Pxq74qGhOqCYI.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/vvNSqIj42qeQ2bvCRBIWKHscrc.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/3ZmXbBKToJifDV9gwcifVd1tEY.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/FNfhX3dt4ChuLJq2PwdlxHO7PU.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/g0c8vEViiXNlKAgI4Ymmk3Ig.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/efTfQcBJ53kM2pB1hezSZ3RDUFs.woff2",
				weight: "900",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
		],
	},
];
var css3 = [
	`.framer-j5VcY .framer-styles-preset-jyira9:not(.rich-text-wrapper), .framer-j5VcY .framer-styles-preset-jyira9.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
	`@media (max-width: 1199px) and (min-width: 810px) { .framer-j5VcY .framer-styles-preset-jyira9:not(.rich-text-wrapper), .framer-j5VcY .framer-styles-preset-jyira9.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
	`@media (max-width: 809px) and (min-width: 0px) { .framer-j5VcY .framer-styles-preset-jyira9:not(.rich-text-wrapper), .framer-j5VcY .framer-styles-preset-jyira9.rich-text-wrapper h1 { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Inter", sans-serif; --framer-font-family-bold-italic: "Inter", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 700; --framer-letter-spacing: -0.03em; --framer-line-height: 1.1em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-404da5a0-b6b9-407a-b3f1-b45132783493, #111111); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; } }`,
];
var className3 = "framer-j5VcY";

// /:https://framerusercontent.com/modules/8Whuce2ANLDhAOylWVwh/w9kzmftgfg2xBxdjWToZ/sHFFwTk7_.js
var cycleOrder = ["ba_OnkpJh", "J4KLspDmY", "sZ0ln4r6r", "C7yX_G6cG"];
var serializationHash = "framer-glIn0";
var variantClassNames = {
	ba_OnkpJh: "framer-v-zt9xbz",
	C7yX_G6cG: "framer-v-1ny1wwt",
	J4KLspDmY: "framer-v-c2ocm7",
	sZ0ln4r6r: "framer-v-bvnsg6",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Tablet - Hovered": "C7yX_G6cG",
	"Tablet - Primary": "sZ0ln4r6r",
	Default: "ba_OnkpJh",
	Hover: "J4KLspDmY",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ba_OnkpJh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ba_OnkpJh",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnterogjitt = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("J4KLspDmY");
	});
	const onMouseLeave1jkyvu1 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("ba_OnkpJh");
	});
	const onMouseEnter11h4jmn = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("C7yX_G6cG");
	});
	const onMouseLeave17d1ptj = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("sZ0ln4r6r");
	});
	const sharedStyleClassNames = [className2, className3, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "J4KLspDmY") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "C7yX_G6cG") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-zt9xbz",
							className4,
							classNames,
						)}
						data-framer-name={"Default"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"ba_OnkpJh"}
						onMouseEnter={onMouseEnterogjitt}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								C7yX_G6cG: {
									"data-framer-name": "Tablet - Hovered",
									onMouseEnter: void 0,
									onMouseLeave: onMouseLeave17d1ptj,
								},
								J4KLspDmY: {
									"data-framer-name": "Hover",
									onMouseEnter: void 0,
									onMouseLeave: onMouseLeave1jkyvu1,
								},
								sZ0ln4r6r: {
									"data-framer-name": "Tablet - Primary",
									onMouseEnter: onMouseEnter11h4jmn,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1xznyql"}
							layoutDependency={layoutDependency}
							layoutId={"itDRPPj7j"}
						>
							<SVG
								className={"framer-1cjhdz0"}
								data-framer-name={"back"}
								layoutDependency={layoutDependency}
								layoutId={"lB6ceM8yr"}
								requiresOverflowVisible={true}
								svg={
									'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 468 361" overflow="visible"><g><defs><path d="M 432 24 C 451.882 24 468 40.118 468 60 L 468 325 C 468 344.882 451.882 361 432 361 L 36 361 C 16.118 361 0 344.882 0 325 L 0 24 C 0 10.745 10.745 0 24 0 L 217 0 C 230.255 0 241 10.745 241 24 Z M 0 132 C 0 132 0 132 0 132 Z" id="a1294z"></path><filter id="a1296z" filterUnits="objectBoundingBox" x="-1.4%" y="-2.3%" width="102.6%" height="104.5%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1299z"></feOffset><feGaussianBlur stdDeviation="1" in="a1299z" result="a1300z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1301z"></feFlood><feComposite in="a1301z" in2="a1300z" operator="in" result="a1297z"></feComposite></filter><linearGradient id="idslB6ceM8yr_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1298z" x="-1.4%" y="-2.3%" width="102.6%" height="104.5%"><rect x="-1.4%" y="-2.3%" width="102.6%" height="104.5%" fill="white"></rect><use href="#a1294z" fill="black"></use></mask><g filter="url(#a1296z)" mask="url(#a1298z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1294z" clip-path="url(#a1295z)"></use></g><use xlink:href="#a1294z" fill="url(#idslB6ceM8yr_1g-1000421650)" clip-path="url(#a1295z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>'
								}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										C7yX_G6cG: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 388.953 300.619" overflow="visible"><g><defs><path d="M 352.953 20 C 372.835 20 388.953 36.118 388.953 56 L 388.953 264.619 C 388.953 284.501 372.835 300.619 352.953 300.619 L 36 300.619 C 16.118 300.619 0 284.501 0 264.619 L 0 24 C 0 10.745 10.745 0 24 0 L 176.294 0 C 188.186 0 198.058 8.649 199.962 20 Z M 0 105.901 C 0 105.901 0 105.901 0 105.901 Z" id="a1318z"></path><filter id="a1320z" filterUnits="objectBoundingBox" x="-1.6%" y="-2.8%" width="103.2%" height="105.4%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1323z"></feOffset><feGaussianBlur stdDeviation="1" in="a1323z" result="a1324z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1325z"></feFlood><feComposite in="a1325z" in2="a1324z" operator="in" result="a1321z"></feComposite></filter><linearGradient id="idsC7yX_G6cGlB6ceM8yr_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1322z" x="-1.6%" y="-2.8%" width="103.2%" height="105.4%"><rect x="-1.6%" y="-2.8%" width="103.2%" height="105.4%" fill="white"></rect><use href="#a1318z" fill="black"></use></mask><g filter="url(#a1320z)" mask="url(#a1322z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1318z" clip-path="url(#a1319z)"></use></g><use xlink:href="#a1318z" fill="url(#idsC7yX_G6cGlB6ceM8yr_1g-1000421650)" clip-path="url(#a1319z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
										},
										J4KLspDmY: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 468 361" overflow="visible"><g><defs><path d="M 432 24 C 451.882 24 468 40.118 468 60 L 468 325 C 468 344.882 451.882 361 432 361 L 36 361 C 16.118 361 0 344.882 0 325 L 0 24 C 0 10.745 10.745 0 24 0 L 217 0 C 230.255 0 241 10.745 241 24 Z M 0 132 C 0 132 0 132 0 132 Z" id="a1302z"></path><filter id="a1304z" filterUnits="objectBoundingBox" x="-1.4%" y="-2.3%" width="102.6%" height="104.5%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1307z"></feOffset><feGaussianBlur stdDeviation="1" in="a1307z" result="a1308z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1309z"></feFlood><feComposite in="a1309z" in2="a1308z" operator="in" result="a1305z"></feComposite></filter><linearGradient id="idsJ4KLspDmYlB6ceM8yr_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1306z" x="-1.4%" y="-2.3%" width="102.6%" height="104.5%"><rect x="-1.4%" y="-2.3%" width="102.6%" height="104.5%" fill="white"></rect><use href="#a1302z" fill="black"></use></mask><g filter="url(#a1304z)" mask="url(#a1306z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1302z" clip-path="url(#a1303z)"></use></g><use xlink:href="#a1302z" fill="url(#idsJ4KLspDmYlB6ceM8yr_1g-1000421650)" clip-path="url(#a1303z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
										},
										sZ0ln4r6r: {
											svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 388.953 300.619" overflow="visible"><g><defs><path d="M 352.953 20 C 372.835 20 388.953 36.118 388.953 56 L 388.953 264.619 C 388.953 284.501 372.835 300.619 352.953 300.619 L 36 300.619 C 16.118 300.619 0 284.501 0 264.619 L 0 24 C 0 10.745 10.745 0 24 0 L 176.294 0 C 188.186 0 198.058 8.649 199.962 20 Z M 0 105.901 C 0 105.901 0 105.901 0 105.901 Z" id="a1310z"></path><filter id="a1312z" filterUnits="objectBoundingBox" x="-1.6%" y="-2.8%" width="103.2%" height="105.4%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1315z"></feOffset><feGaussianBlur stdDeviation="1" in="a1315z" result="a1316z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1317z"></feFlood><feComposite in="a1317z" in2="a1316z" operator="in" result="a1313z"></feComposite></filter><linearGradient id="idssZ0ln4r6rlB6ceM8yr_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1314z" x="-1.6%" y="-2.8%" width="103.2%" height="105.4%"><rect x="-1.6%" y="-2.8%" width="103.2%" height="105.4%" fill="white"></rect><use href="#a1310z" fill="black"></use></mask><g filter="url(#a1312z)" mask="url(#a1314z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1310z" clip-path="url(#a1311z)"></use></g><use xlink:href="#a1310z" fill="url(#idssZ0ln4r6rlB6ceM8yr_1g-1000421650)" clip-path="url(#a1311z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SVG
									className={"framer-1ksflnj"}
									layoutDependency={layoutDependency}
									layoutId={"X9F0hA3xt"}
									radius={36}
									requiresOverflowVisible={true}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 468 337" overflow="visible"><g><defs><path d="M 0 36 C 0 16.118 16.118 0 36 0 L 432 0 C 451.882 0 468 16.118 468 36 L 468 301 C 468 320.882 451.882 337 432 337 L 36 337 C 16.118 337 0 320.882 0 301 Z" id="a1326z"></path><filter id="a1328z" filterUnits="objectBoundingBox" x="-1.4%" y="-2.5%" width="102.6%" height="104.8%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1331z"></feOffset><feGaussianBlur stdDeviation="1" in="a1331z" result="a1332z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1333z"></feFlood><feComposite in="a1333z" in2="a1332z" operator="in" result="a1329z"></feComposite></filter><linearGradient id="idsX9F0hA3xt_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1330z" x="-1.4%" y="-2.5%" width="102.6%" height="104.8%"><rect x="-1.4%" y="-2.5%" width="102.6%" height="104.8%" fill="white"></rect><use href="#a1326z" fill="black"></use></mask><g filter="url(#a1328z)" mask="url(#a1330z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1326z" clip-path="url(#a1327z)"></use></g><use xlink:href="#a1326z" fill="url(#idsX9F0hA3xt_1g-1000421650)" clip-path="url(#a1327z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>'
									}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											C7yX_G6cG: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 388.953 280.619" overflow="visible"><g><defs><path d="M 0 36 C 0 16.118 16.118 0 36 0 L 352.953 0 C 372.835 0 388.953 16.118 388.953 36 L 388.953 244.619 C 388.953 264.501 372.835 280.619 352.953 280.619 L 36 280.619 C 16.118 280.619 0 264.501 0 244.619 Z" id="a1350z"></path><filter id="a1352z" filterUnits="objectBoundingBox" x="-1.6%" y="-3.0%" width="103.2%" height="105.8%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1355z"></feOffset><feGaussianBlur stdDeviation="1" in="a1355z" result="a1356z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1357z"></feFlood><feComposite in="a1357z" in2="a1356z" operator="in" result="a1353z"></feComposite></filter><linearGradient id="idsC7yX_G6cGX9F0hA3xt_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1354z" x="-1.6%" y="-3.0%" width="103.2%" height="105.8%"><rect x="-1.6%" y="-3.0%" width="103.2%" height="105.8%" fill="white"></rect><use href="#a1350z" fill="black"></use></mask><g filter="url(#a1352z)" mask="url(#a1354z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1350z" clip-path="url(#a1351z)"></use></g><use xlink:href="#a1350z" fill="url(#idsC7yX_G6cGX9F0hA3xt_1g-1000421650)" clip-path="url(#a1351z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
											J4KLspDmY: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 468 337" overflow="visible"><g><defs><path d="M 0 36 C 0 16.118 16.118 0 36 0 L 432 0 C 451.882 0 468 16.118 468 36 L 468 301 C 468 320.882 451.882 337 432 337 L 36 337 C 16.118 337 0 320.882 0 301 Z" id="a1334z"></path><filter id="a1336z" filterUnits="objectBoundingBox" x="-1.4%" y="-2.5%" width="102.6%" height="104.8%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1339z"></feOffset><feGaussianBlur stdDeviation="1" in="a1339z" result="a1340z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1341z"></feFlood><feComposite in="a1341z" in2="a1340z" operator="in" result="a1337z"></feComposite></filter><linearGradient id="idsJ4KLspDmYX9F0hA3xt_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1338z" x="-1.4%" y="-2.5%" width="102.6%" height="104.8%"><rect x="-1.4%" y="-2.5%" width="102.6%" height="104.8%" fill="white"></rect><use href="#a1334z" fill="black"></use></mask><g filter="url(#a1336z)" mask="url(#a1338z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1334z" clip-path="url(#a1335z)"></use></g><use xlink:href="#a1334z" fill="url(#idsJ4KLspDmYX9F0hA3xt_1g-1000421650)" clip-path="url(#a1335z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
											sZ0ln4r6r: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 388.953 280.619" overflow="visible"><g><defs><path d="M 0 36 C 0 16.118 16.118 0 36 0 L 352.953 0 C 372.835 0 388.953 16.118 388.953 36 L 388.953 244.619 C 388.953 264.501 372.835 280.619 352.953 280.619 L 36 280.619 C 16.118 280.619 0 264.501 0 244.619 Z" id="a1342z"></path><filter id="a1344z" filterUnits="objectBoundingBox" x="-1.6%" y="-3.0%" width="103.2%" height="105.8%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1347z"></feOffset><feGaussianBlur stdDeviation="1" in="a1347z" result="a1348z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1349z"></feFlood><feComposite in="a1349z" in2="a1348z" operator="in" result="a1345z"></feComposite></filter><linearGradient id="idssZ0ln4r6rX9F0hA3xt_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1346z" x="-1.6%" y="-3.0%" width="103.2%" height="105.8%"><rect x="-1.6%" y="-3.0%" width="103.2%" height="105.8%" fill="white"></rect><use href="#a1342z" fill="black"></use></mask><g filter="url(#a1344z)" mask="url(#a1346z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1342z" clip-path="url(#a1343z)"></use></g><use xlink:href="#a1342z" fill="url(#idssZ0ln4r6rX9F0hA3xt_1g-1000421650)" clip-path="url(#a1343z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<SVG
									className={"framer-1458uc1"}
									layoutDependency={layoutDependency}
									layoutId={"RUqhBdPmP"}
									radius={24}
									requiresOverflowVisible={true}
									svg={
										'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 241 156" overflow="visible"><g><defs><path d="M 0 24 C 0 10.745 10.745 0 24 0 L 217 0 C 230.255 0 241 10.745 241 24 L 241 132 C 241 145.255 230.255 156 217 156 L 24 156 C 10.745 156 0 145.255 0 132 Z" id="a1358z"></path><filter id="a1360z" filterUnits="objectBoundingBox" x="-2.7%" y="-5.4%" width="105.1%" height="110.4%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1363z"></feOffset><feGaussianBlur stdDeviation="1" in="a1363z" result="a1364z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1365z"></feFlood><feComposite in="a1365z" in2="a1364z" operator="in" result="a1361z"></feComposite></filter><linearGradient id="idsRUqhBdPmP_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1362z" x="-2.7%" y="-5.4%" width="105.1%" height="110.4%"><rect x="-2.7%" y="-5.4%" width="105.1%" height="110.4%" fill="white"></rect><use href="#a1358z" fill="black"></use></mask><g filter="url(#a1360z)" mask="url(#a1362z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1358z" clip-path="url(#a1359z)"></use></g><use xlink:href="#a1358z" fill="url(#idsRUqhBdPmP_1g-1000421650)" clip-path="url(#a1359z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>'
									}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											C7yX_G6cG: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 200.294 129.901" overflow="visible"><g><defs><path d="M 0 24 C 0 10.745 10.745 0 24 0 L 176.294 0 C 189.549 0 200.294 10.745 200.294 24 L 200.294 105.901 C 200.294 119.155 189.549 129.901 176.294 129.901 L 24 129.901 C 10.745 129.901 0 119.155 0 105.901 Z" id="a1382z"></path><filter id="a1384z" filterUnits="objectBoundingBox" x="-3.2%" y="-6.4%" width="106.1%" height="112.5%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1387z"></feOffset><feGaussianBlur stdDeviation="1" in="a1387z" result="a1388z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1389z"></feFlood><feComposite in="a1389z" in2="a1388z" operator="in" result="a1385z"></feComposite></filter><linearGradient id="idsC7yX_G6cGRUqhBdPmP_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1386z" x="-3.2%" y="-6.4%" width="106.1%" height="112.5%"><rect x="-3.2%" y="-6.4%" width="106.1%" height="112.5%" fill="white"></rect><use href="#a1382z" fill="black"></use></mask><g filter="url(#a1384z)" mask="url(#a1386z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1382z" clip-path="url(#a1383z)"></use></g><use xlink:href="#a1382z" fill="url(#idsC7yX_G6cGRUqhBdPmP_1g-1000421650)" clip-path="url(#a1383z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
											J4KLspDmY: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 241 156" overflow="visible"><g><defs><path d="M 0 24 C 0 10.745 10.745 0 24 0 L 217 0 C 230.255 0 241 10.745 241 24 L 241 132 C 241 145.255 230.255 156 217 156 L 24 156 C 10.745 156 0 145.255 0 132 Z" id="a1366z"></path><filter id="a1368z" filterUnits="objectBoundingBox" x="-2.7%" y="-5.4%" width="105.1%" height="110.4%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1371z"></feOffset><feGaussianBlur stdDeviation="1" in="a1371z" result="a1372z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1373z"></feFlood><feComposite in="a1373z" in2="a1372z" operator="in" result="a1369z"></feComposite></filter><linearGradient id="idsJ4KLspDmYRUqhBdPmP_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1370z" x="-2.7%" y="-5.4%" width="105.1%" height="110.4%"><rect x="-2.7%" y="-5.4%" width="105.1%" height="110.4%" fill="white"></rect><use href="#a1366z" fill="black"></use></mask><g filter="url(#a1368z)" mask="url(#a1370z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1366z" clip-path="url(#a1367z)"></use></g><use xlink:href="#a1366z" fill="url(#idsJ4KLspDmYRUqhBdPmP_1g-1000421650)" clip-path="url(#a1367z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
											sZ0ln4r6r: {
												svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 200.294 129.901" overflow="visible"><g><defs><path d="M 0 24 C 0 10.745 10.745 0 24 0 L 176.294 0 C 189.549 0 200.294 10.745 200.294 24 L 200.294 105.901 C 200.294 119.155 189.549 129.901 176.294 129.901 L 24 129.901 C 10.745 129.901 0 119.155 0 105.901 Z" id="a1374z"></path><filter id="a1376z" filterUnits="objectBoundingBox" x="-3.2%" y="-6.4%" width="106.1%" height="112.5%"><feOffset dx="0" dy="2" in="SourceAlpha" result="a1379z"></feOffset><feGaussianBlur stdDeviation="1" in="a1379z" result="a1380z"></feGaussianBlur><feFlood flood-color="rgba(0,0,0,0.25)" result="a1381z"></feFlood><feComposite in="a1381z" in2="a1380z" operator="in" result="a1377z"></feComposite></filter><linearGradient id="idssZ0ln4r6rRUqhBdPmP_1g-1000421650" x1="0.49751243781094523" x2="0.5024875621890548" y1="0" y2="1"><stop offset="0" stop-color="rgb(120, 120, 120)" stop-opacity="1"></stop><stop offset="1" stop-color="rgb(204, 204, 204)" stop-opacity="1"></stop></linearGradient></defs><mask id="a1378z" x="-3.2%" y="-6.4%" width="106.1%" height="112.5%"><rect x="-3.2%" y="-6.4%" width="106.1%" height="112.5%" fill="white"></rect><use href="#a1374z" fill="black"></use></mask><g filter="url(#a1376z)" mask="url(#a1378z)"><use stroke-width="1" stroke="black" fill="black" xlink:href="#a1374z" clip-path="url(#a1375z)"></use></g><use xlink:href="#a1374z" fill="url(#idssZ0ln4r6rRUqhBdPmP_1g-1000421650)" clip-path="url(#a1375z)" stroke-width="1" stroke="rgb(236, 236, 236)"></use></g></svg>',
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</SVG>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1823l2l"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"mWVdHcIsf"}
								style={{
									"--extracted-r6o4lv": "rgba(71, 71, 71, 0.5)",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1o5tu90"}
										data-styles-preset={"cKcUkx2tM"}
										dir={"auto"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, rgba(71, 71, 71, 0.5))",
										}}
									>
										{"Pat Sricome"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<Image
								background={{
									alt: "",
									fit: "fit",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											0 +
											((componentViewport?.height || 410) - 0) -
											313,
									),
									pixelHeight: 476,
									pixelWidth: 409,
									positionX: "center",
									positionY: "center",
									sizes: "400px",
									src: "https://framerusercontent.com/images/134a4jJLBs0joe8e4siX5Di0nY.svg?width=409&height=476",
								}}
								className={"framer-ky10bx"}
								layoutDependency={layoutDependency}
								layoutId={"E_69g_c1y"}
								style={{
									rotate: 19,
								}}
								variants={{
									C7yX_G6cG: {
										rotate: 0,
									},
									J4KLspDmY: {
										rotate: -6,
									},
								}}
								{...addPropertyOverrides(
									{
										C7yX_G6cG: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 410) - 0 - 410) /
																2) +
														-141,
												),
												pixelHeight: 476,
												pixelWidth: 409,
												positionX: "center",
												positionY: "center",
												sizes: "333px",
												src: "https://framerusercontent.com/images/134a4jJLBs0joe8e4siX5Di0nY.svg?width=409&height=476",
											},
										},
										J4KLspDmY: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0 + -102,
												),
												pixelHeight: 476,
												pixelWidth: 409,
												positionX: "center",
												positionY: "center",
												sizes: "400px",
												src: "https://framerusercontent.com/images/134a4jJLBs0joe8e4siX5Di0nY.svg?width=409&height=476",
											},
										},
										sZ0ln4r6r: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) +
														(0 +
															((componentViewport?.height || 200) - 0 - 410) /
																2) +
														64,
												),
												pixelHeight: 476,
												pixelWidth: 409,
												positionX: "center",
												positionY: "center",
												sizes: "333px",
												src: "https://framerusercontent.com/images/134a4jJLBs0joe8e4siX5Di0nY.svg?width=409&height=476",
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							{isDisplayed() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-sq8pc1"}
									draggable={"true"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"kJ48AijJe"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										rotate: -8,
										scale: 0.8,
										skewY: -6,
										transformPerspective: 1644,
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h1
											className={"framer-styles-preset-jyira9"}
											data-styles-preset={"xOozWzlxf"}
											dir={"auto"}
										>
											{"Hi, I'm Pat Sricome"}
										</motion.h1>
										<motion.h1
											className={"framer-styles-preset-jyira9"}
											data-styles-preset={"xOozWzlxf"}
											dir={"auto"}
										>
											{"a UI/UX designer"}
										</motion.h1>
									</React.Fragment>
								</RichText>
							)}
							<motion.div
								className={"framer-1swkz22"}
								data-border={true}
								data-framer-name={"Front"}
								layoutDependency={layoutDependency}
								layoutId={"ga4yCyrBE"}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgb(236, 236, 236)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backdropFilter: "blur(5px)",
									backgroundColor: "rgba(236, 236, 236, 0.5)",
									borderBottomLeftRadius: 24,
									borderBottomRightRadius: 24,
									borderTopLeftRadius: 24,
									borderTopRightRadius: 24,
									boxShadow:
										"0px -1px 0px 0px rgba(112, 112, 112, 0.5), inset 0px 1px 0px 0px rgb(76, 76, 76), 1px 15px 40px 4px rgb(76, 76, 76)",
									originY: 1,
									rotateX: -30,
									transformPerspective: 1571,
									WebkitBackdropFilter: "blur(5px)",
								}}
								variants={{
									J4KLspDmY: {
										rotateX: -60,
									},
								}}
							>
								<Image
									background={{
										alt: "",
										backgroundSize: 0.5,
										fit: "tile",
										intrinsicHeight: 112,
										intrinsicWidth: 135,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												((componentViewport?.height || 410) - 0) -
												321 +
												0,
										),
										pixelHeight: 256,
										pixelWidth: 256,
										positionX: "left",
										positionY: "top",
										sizes: componentViewport?.width || "100vw",
										src: "https://framerusercontent.com/images/6mcf62RlDfRfU61Yg5vb2pefpi4.png?width=256&height=256",
									}}
									className={"framer-1vvqjv9"}
									data-framer-name={"Blur"}
									layoutDependency={layoutDependency}
									layoutId={"YguUtPI8g"}
									style={{
										backdropFilter: "blur(5px)",
										filter: "drop-shadow(0px 1px 1px rgba(0, 0, 0, 0.1))",
										opacity: 0.2,
										originY: 1,
										transformPerspective: 1763,
										WebkitBackdropFilter: "blur(5px)",
										WebkitFilter: "drop-shadow(0px 1px 1px rgba(0, 0, 0, 0.1))",
									}}
									{...addPropertyOverrides(
										{
											C7yX_G6cG: {
												background: {
													alt: "",
													backgroundSize: 0.5,
													fit: "tile",
													intrinsicHeight: 112,
													intrinsicWidth: 135,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(0 +
																((componentViewport?.height || 410) - 0 - 410) /
																	2) +
															57 +
															0,
													),
													pixelHeight: 256,
													pixelWidth: 256,
													positionX: "left",
													positionY: "top",
													sizes: "388px",
													src: "https://framerusercontent.com/images/6mcf62RlDfRfU61Yg5vb2pefpi4.png?width=256&height=256",
												},
											},
											sZ0ln4r6r: {
												background: {
													alt: "",
													backgroundSize: 0.5,
													fit: "tile",
													intrinsicHeight: 112,
													intrinsicWidth: 135,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) +
															(0 +
																((componentViewport?.height || 200) - 0 - 410) /
																	2) +
															57 +
															0,
													),
													pixelHeight: 256,
													pixelWidth: 256,
													positionX: "left",
													positionY: "top",
													sizes: "388px",
													src: "https://framerusercontent.com/images/6mcf62RlDfRfU61Yg5vb2pefpi4.png?width=256&height=256",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1bbvyae"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"IUXDpmpEl"}
									style={{
										"--extracted-1of0zx5": "rgb(255, 255, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										textShadow: "1px -1px 2px rgba(0,0,0,0.25)",
									}}
									variants={{
										C7yX_G6cG: {
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										},
										sZ0ln4r6r: {
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											C7yX_G6cG: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1o5tu90"}
															data-styles-preset={"cKcUkx2tM"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Portfolio 2026"}
														</motion.p>
													</React.Fragment>
												),
											},
											sZ0ln4r6r: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1o5tu90"}
															data-styles-preset={"cKcUkx2tM"}
															dir={"auto"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"Portfolio 2026"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h2
											className={"framer-styles-preset-8kwqzc"}
											data-styles-preset={"APT599laW"}
											dir={"auto"}
											style={{
												"--framer-text-color":
													"var(--extracted-1of0zx5, rgb(255, 255, 255))",
											}}
										>
											{"Portfolio 2026"}
										</motion.h2>
									</React.Fragment>
								</RichText>
								{isDisplayed1() && (
									<RichText
										__fromCanvasComponent={true}
										className={"framer-a6akz7"}
										draggable={"true"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"mfSamhyWk"}
										style={{
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
											backdropFilter: "blur(32px)",
											scale: 0.8,
											skewX: 4,
											skewY: 2,
											transformPerspective: 1964,
											WebkitBackdropFilter: "blur(32px)",
										}}
										transformTemplate={transformTemplate1}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.h1
												className={"framer-styles-preset-jyira9"}
												data-styles-preset={"xOozWzlxf"}
												dir={"auto"}
											>
												{"Hi, I'm Pat Sricome"}
											</motion.h1>
											<motion.h1
												className={"framer-styles-preset-jyira9"}
												data-styles-preset={"xOozWzlxf"}
												dir={"auto"}
											>
												{"a UI/UX designer"}
											</motion.h1>
										</React.Fragment>
									</RichText>
								)}
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-glIn0.framer-1frg3ts, .framer-glIn0 .framer-1frg3ts { display: block; }",
	".framer-glIn0.framer-zt9xbz { gap: 10px; height: 410px; overflow: visible; position: relative; width: 468px; }",
	".framer-glIn0 .framer-1xznyql { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-glIn0 .framer-1cjhdz0 { height: 361px; left: 0px; position: absolute; top: 49px; width: 468px; }",
	".framer-glIn0 .framer-1ksflnj { height: 337px; left: 0px; position: absolute; top: 24px; width: 468px; }",
	".framer-glIn0 .framer-1458uc1 { height: 156px; left: 0px; position: absolute; top: 0px; width: 241px; }",
	".framer-glIn0 .framer-1823l2l { flex: none; height: auto; left: 20px; position: absolute; top: 57px; white-space: pre; width: auto; }",
	".framer-glIn0 .framer-ky10bx { bottom: 13px; flex: none; height: 300px; left: calc(54.4871794871795% - 400px / 2); position: absolute; width: 400px; }",
	".framer-glIn0 .framer-sq8pc1 { flex: none; height: auto; position: absolute; right: -42px; top: -101px; white-space: pre; width: auto; }",
	".framer-glIn0 .framer-1swkz22 { bottom: 0px; flex: none; height: 321px; left: 0px; overflow: hidden; position: absolute; right: 0px; transform-style: preserve-3d; will-change: var(--framer-will-change-override, transform); z-index: 6; }",
	".framer-glIn0 .framer-1vvqjv9 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; transform-style: preserve-3d; }",
	".framer-glIn0 .framer-1bbvyae { flex: none; height: auto; left: 20px; position: absolute; top: 17px; white-space: pre; width: auto; }",
	".framer-glIn0 .framer-a6akz7 { flex: none; height: auto; left: 49%; position: absolute; top: -280px; white-space: pre; width: auto; }",
	".framer-glIn0.framer-v-c2ocm7 .framer-ky10bx { bottom: unset; left: -142px; top: -102px; }",
	".framer-glIn0.framer-v-bvnsg6.framer-zt9xbz, .framer-glIn0.framer-v-1ny1wwt.framer-zt9xbz { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: center; padding: 0px; width: min-content; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1xznyql, .framer-glIn0.framer-v-1ny1wwt .framer-1xznyql { bottom: unset; height: 410px; left: unset; position: relative; right: unset; top: unset; width: 428px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1cjhdz0, .framer-glIn0.framer-v-1ny1wwt .framer-1cjhdz0 { height: 301px; left: -4px; top: 24px; width: 389px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1ksflnj, .framer-glIn0.framer-v-1ny1wwt .framer-1ksflnj { height: 281px; top: 20px; width: 389px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1458uc1, .framer-glIn0.framer-v-1ny1wwt .framer-1458uc1 { height: 130px; width: 201px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1823l2l, .framer-glIn0.framer-v-1ny1wwt .framer-1823l2l { left: 12px; top: 31px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-ky10bx { bottom: unset; height: 250px; left: 41px; top: calc(46.09756097560978% - 250px / 2); width: 333px; }",
	".framer-glIn0.framer-v-bvnsg6 .framer-1swkz22 { bottom: unset; height: 268px; left: -4px; right: unset; top: calc(46.58536585365856% - 268px / 2); width: 388px; }",
	".framer-glIn0.framer-v-1ny1wwt .framer-ky10bx { bottom: unset; height: 250px; left: 26px; top: -141px; width: 333px; }",
	".framer-glIn0.framer-v-1ny1wwt .framer-1swkz22 { bottom: unset; height: 268px; left: -4px; overflow: visible; right: unset; top: calc(46.58536585365856% - 268px / 2); width: 388px; will-change: unset; }",
	...css2,
	...css3,
	...css,
	'.framer-glIn0[data-border="true"]::after, .framer-glIn0 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramersHFFwTk7_ = withCSS(Component, css4, "framer-glIn0");
var stdin_default = FramersHFFwTk7_;
FramersHFFwTk7_.displayName = "Folder new";
FramersHFFwTk7_.defaultProps = {
	height: 410,
	width: 468,
};
addPropertyControls(FramersHFFwTk7_, {
	variant: {
		options: ["ba_OnkpJh", "J4KLspDmY", "sZ0ln4r6r", "C7yX_G6cG"],
		optionTitles: ["Default", "Hover", "Tablet - Primary", "Tablet - Hovered"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramersHFFwTk7_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:folder-new
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "sZ0ln4r6r",
	xl: "ba_OnkpJh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a388a4e8c1271596c25793932fb9581943efabb7f04a942d74fc0b8c62dc4850"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FolderNewFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a388a4e8c1271596c25793932fb9581943efabb7f04a942d74fc0b8c62dc4850"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var folder_new_default = ComponentWithRoot;
export { folder_new_default as default };
