// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project a388a4e8c1271596 "Pat's", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Let's Talk Card' | 'Let's Talk Card - Hover' // Variant
 * portraitImage?: {src: string, srcSet?: string, alt?: string} // Portrait Image
 * title?: string // Title
 * title2?: string // Title 2
 * desc?: string // Desc
 * project?: string // Project
 * buttonText?: string // Button Text
 * link?: string // Link
 * newTab?: boolean // New Tab
}} Props

 */
import { routes } from "./chunks/chunk-LKSUI2VU.js";

// virtual:let-s-talk-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/WOFBSbjm7HQK5NIkykLB/sdgGch3jYbofE9ryd4qr/fnig4zHET.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/2WQzq084DzoFmwmk0fUI/sBT0012yPWvPR8ixbuvU/xWxFPmdWu.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef2(function (props, ref) {
	return (
		<svg {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG {...rest} layoutId={layoutId} ref={ref}>
			{children}
		</MotionSVG>
	) : (
		<svg {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 7 L 18 7 M 18 7 L 11 0 M 18 7 L 11 14" fill="transparent" height="14px" id="OkGDCS1yo" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--1ww558a, 2)" stroke="var(--4rxgx6, black)" transform="translate(3 5)" width="18px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		CRY1Fpez4: color ?? props.CRY1Fpez4 ?? "rgb(0, 0, 0)",
		vet7gqNu_: width1 ?? props.vet7gqNu_ ?? 2,
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		CRY1Fpez4,
		vet7gqNu_,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2047441354", svg);
	return (
		<SVG
			{...restProps}
			className={cx("framer-m6IyR", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1ww558a": vet7gqNu_,
				"--4rxgx6": CRY1Fpez4,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use href={href} />
		</SVG>
	);
});
var css = [
	`.framer-m6IyR { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-m6IyR");
Icon.displayName = "Arrow Right";
var stdin_default = Icon;
addPropertyControls(Icon, {
	CRY1Fpez4: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	vet7gqNu_: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 4,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});

// /:https://framerusercontent.com/modules/nxGYgwyjsrceQy8Sc9rk/ITWF3D5dHrPCg2XnxEBG/EWgHGx0mg.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"GF;Instrument Sans-regular",
	"GF;Instrument Sans-700",
	"GF;Instrument Sans-700italic",
	"GF;Instrument Sans-italic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Instrument Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "Instrument Sans",
				url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSTF-QfwmS0v3_7Y.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Instrument Sans",
				openType: true,
				source: "google",
				style: "normal",
				uiFamilyName: "Instrument Sans",
				url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSQi_gfwmS0v3_7Y.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Instrument Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "Instrument Sans",
				url: "https://fonts.gstatic.com/s/instrumentsans/v4/pxigypc9vsFDm051Uf6KVwgkfoSbSnNPooZAN0lInHGpCWNE27lgU-XJojENugixkywN2u7YUwU.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Instrument Sans",
				openType: true,
				source: "google",
				style: "italic",
				uiFamilyName: "Instrument Sans",
				url: "https://fonts.gstatic.com/s/instrumentsans/v4/pxigypc9vsFDm051Uf6KVwgkfoSbSnNPooZAN0lInHGpCWNE27lgU-XJojENuu-2kywN2u7YUwU.woff2",
				weight: "400",
			},
		],
	},
];
var css2 = [
	`.framer-M3D7K .framer-styles-preset-v7m4nv:not(.rich-text-wrapper), .framer-M3D7K .framer-styles-preset-v7m4nv.rich-text-wrapper p { --framer-font-family: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-bold-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-family-italic: "Instrument Sans", "Instrument Sans Placeholder", sans-serif; --framer-font-open-type-features: 'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on; --framer-font-size: 10px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.4em; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-923661f6-bb67-400f-9b15-4dbe77975e9c, #71767f); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }`,
];
var className = "framer-M3D7K";

// /:https://framerusercontent.com/modules/WOFBSbjm7HQK5NIkykLB/sdgGch3jYbofE9ryd4qr/fnig4zHET.js
var ArrowRightFonts = getFonts(stdin_default);
var cycleOrder = ["awFU0mrem", "x6sYmpWDs"];
var serializationHash = "framer-3BpKY";
var variantClassNames = {
	awFU0mrem: "framer-v-1sl6m6s",
	x6sYmpWDs: "framer-v-1uu7ksv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Let's Talk Card - Hover": "x6sYmpWDs",
	"Let's Talk Card": "awFU0mrem",
};
var getProps2 = ({
	buttonText,
	desc,
	height,
	id,
	link,
	newTab,
	portraitImage,
	project,
	title,
	title2,
	width,
	...props
}) => {
	return {
		...props,
		btlkH0XLo: desc ?? props.btlkH0XLo ?? "Desc",
		CGQ6RMKTn: project ?? props.CGQ6RMKTn ?? "Project name",
		GpVlhVAOO: title2 ?? props.GpVlhVAOO ?? "Team Lead",
		hC0hXqchb: buttonText ?? props.hC0hXqchb ?? "Read More",
		Lm8fxgKJk: newTab ?? props.Lm8fxgKJk,
		oHdoMzddN: link ?? props.oHdoMzddN,
		pPRfldf4V: title ?? props.pPRfldf4V ?? "Team Lead",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "awFU0mrem",
		XUSUbL2ED: portraitImage ??
			props.XUSUbL2ED ?? {
				alt: "",
				pixelHeight: 1333,
				pixelWidth: 2e3,
				src: "https://framerusercontent.com/images/rRjhAyKijqlXTxzw48Yh5U4LQ.png?width=2000&height=1333",
				srcSet:
					"https://framerusercontent.com/images/rRjhAyKijqlXTxzw48Yh5U4LQ.png?scale-down-to=512&width=2000&height=1333 512w,https://framerusercontent.com/images/rRjhAyKijqlXTxzw48Yh5U4LQ.png?scale-down-to=1024&width=2000&height=1333 1024w,https://framerusercontent.com/images/rRjhAyKijqlXTxzw48Yh5U4LQ.png?width=2000&height=1333 2000w",
			},
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		XUSUbL2ED: XUSUbL2ED2,
		pPRfldf4V: pPRfldf4V2,
		GpVlhVAOO: GpVlhVAOO2,
		btlkH0XLo: btlkH0XLo2,
		CGQ6RMKTn: CGQ6RMKTn2,
		hC0hXqchb: hC0hXqchb2,
		oHdoMzddN: oHdoMzddN2,
		Lm8fxgKJk: Lm8fxgKJk2,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "awFU0mrem",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseEnter1kixqdf = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: true,
		});
		setVariant("x6sYmpWDs");
	});
	const onMouseLeavezwz5lz = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("awFU0mrem");
	});
	const onMouseEnter1b2uuow = activeVariantCallback(async (...args) => {
		setVariant("x6sYmpWDs");
	});
	const onMouseLeave1tc3zfn = activeVariantCallback(async (...args) => {
		setVariant("awFU0mrem");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1sl6m6s",
							className2,
							classNames,
						)}
						data-framer-name={"Let's Talk Card"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"awFU0mrem"}
						onMouseEnter={onMouseEnter1kixqdf}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								x6sYmpWDs: {
									"data-framer-name": "Let's Talk Card - Hover",
									onMouseEnter: void 0,
									onMouseLeave: onMouseLeavezwz5lz,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-17svyrx"}
							data-framer-name={"Portrait Image"}
							layoutDependency={layoutDependency}
							layoutId={"sXozVDx5o"}
							style={{
								backgroundColor:
									"var(--token-ff774584-9e15-420a-a419-bd93e596e83b, rgb(245, 245, 245))",
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
							}}
							variants={{
								x6sYmpWDs: {
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 0,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 0,
								},
							}}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										(componentViewport?.y || 0) +
											(0 + ((componentViewport?.height || 200) - 0 - 200) / 2) +
											8 +
											0,
									),
									pixelHeight: 1333,
									pixelWidth: 2e3,
									sizes: "224px",
									...toResponsiveImage(XUSUbL2ED2),
								}}
								className={"framer-1q3f2kt"}
								data-framer-name={"Portrait Image"}
								layoutDependency={layoutDependency}
								layoutId={"BCfUvbcBo"}
								style={{
									borderBottomLeftRadius: 6,
									borderBottomRightRadius: 6,
									borderTopLeftRadius: 6,
									borderTopRightRadius: 6,
								}}
							/>
						</motion2.div>
						<motion2.div
							className={"framer-qqbmyq"}
							data-framer-name={"Text Section"}
							layoutDependency={layoutDependency}
							layoutId={"HiXhBXG62"}
							style={{
								backgroundColor:
									"var(--token-ff774584-9e15-420a-a419-bd93e596e83b, rgb(245, 245, 245))",
								borderBottomLeftRadius: 12,
								borderBottomRightRadius: 12,
								borderTopLeftRadius: 12,
								borderTopRightRadius: 12,
							}}
							variants={{
								x6sYmpWDs: {
									borderBottomLeftRadius: 0,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 0,
									borderTopRightRadius: 8,
								},
							}}
						>
							<motion2.div
								className={"framer-12miagm"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"aDg6ULljd"}
							>
								<motion2.div
									className={"framer-usg3bo"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"vwOc4NMIP"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-556c256e-b7ca-4b49-afe4-befb44d116b3, rgb(209, 211, 214))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-138ewc6"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"GsX0la9P6"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-923661f6-bb67-400f-9b15-4dbe77975e9c, rgb(108, 113, 121))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={pPRfldf4V2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-v7m4nv"}
												data-styles-preset={"EWgHGx0mg"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-923661f6-bb67-400f-9b15-4dbe77975e9c, rgb(108, 113, 121)))",
												}}
											>
												{"Team Lead"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
								<motion2.div
									className={"framer-11gkuw8"}
									data-border={true}
									layoutDependency={layoutDependency}
									layoutId={"WTwFzMNON"}
									style={{
										"--border-bottom-width": "1px",
										"--border-color":
											"var(--token-556c256e-b7ca-4b49-afe4-befb44d116b3, rgb(209, 211, 214))",
										"--border-left-width": "1px",
										"--border-right-width": "1px",
										"--border-style": "solid",
										"--border-top-width": "1px",
										borderBottomLeftRadius: 4,
										borderBottomRightRadius: 4,
										borderTopLeftRadius: 4,
										borderTopRightRadius: 4,
									}}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-i7j81h"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"CHE28nn7A"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-923661f6-bb67-400f-9b15-4dbe77975e9c, rgb(108, 113, 121))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={GpVlhVAOO2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-v7m4nv"}
												data-styles-preset={"EWgHGx0mg"}
												dir={"auto"}
												style={{
													"--framer-text-alignment": "center",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-923661f6-bb67-400f-9b15-4dbe77975e9c, rgb(108, 113, 121)))",
												}}
											>
												{"Team Lead"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-11t541s"}
								data-framer-name={"Name"}
								layoutDependency={layoutDependency}
								layoutId={"muwVhRk_L"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1v1n44i"}
									fonts={["GF;Instrument Sans-600"]}
									layoutDependency={layoutDependency}
									layoutId={"TFefRoBM_"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={CGQ6RMKTn2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											dir={"auto"}
											style={{
												"--font-selector": "R0Y7SW5zdHJ1bWVudCBTYW5zLTYwMA==",
												"--framer-font-family":
													'"Instrument Sans", "Instrument Sans Placeholder", sans-serif',
												"--framer-font-open-type-features":
													"'blwf' on, 'cv09' on, 'cv03' on, 'cv04' on, 'cv11' on",
												"--framer-font-size": "18px",
												"--framer-font-weight": "600",
												"--framer-letter-spacing": "-0.02em",
												"--framer-line-height": "27px",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0)))",
												"--framer-text-transform": "capitalize",
											}}
										>
											{"Soyian Rahman"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-woq4xh"}
									fonts={["GF;Instrument Sans-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"cvOITcKfP"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={btlkH0XLo2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											dir={"auto"}
											style={{
												"--font-selector":
													"R0Y7SW5zdHJ1bWVudCBTYW5zLXJlZ3VsYXI=",
												"--framer-font-family":
													'"Instrument Sans", "Instrument Sans Placeholder", sans-serif',
												"--framer-font-size": "12px",
												"--framer-line-height": "18px",
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0)))",
											}}
										>
											{"At Obliq\xAE"}
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
							<motion2.div
								className={"framer-10k0v5p"}
								layoutDependency={layoutDependency}
								layoutId={"UPN7c8gtw"}
							>
								<Link
									href={oHdoMzddN2}
									motionChild={true}
									nodeId={"rVHM1Qh3C"}
									openInNewTab={Lm8fxgKJk2}
									scopeId={"fnig4zHET"}
								>
									<motion2.a
										className={"framer-pk5f20 framer-1lp2ghf"}
										data-framer-name={"Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"rVHM1Qh3C"}
										onMouseEnter={onMouseEnter1b2uuow}
										{...addPropertyOverrides(
											{
												x6sYmpWDs: {
													onMouseLeave: onMouseLeave1tc3zfn,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</Link>
								<Link
									href={oHdoMzddN2}
									motionChild={true}
									nodeId={"GaKRVdZBV"}
									openInNewTab={Lm8fxgKJk2}
									scopeId={"fnig4zHET"}
								>
									<motion2.a
										className={"framer-krhmgl framer-1lp2ghf"}
										data-framer-name={"Button"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"GaKRVdZBV"}
										onMouseEnter={onMouseEnter1b2uuow}
									>
										{_jsx2(stdin_default, {
											animated: true,
											className: "framer-jxsjis",
											layoutDependency,
											layoutId: "Z4h6L9jk3",
											style: {
												"--1ww558a": 2,
												"--4rxgx6": "rgb(0, 0, 0)",
											},
											variants: {
												x6sYmpWDs: {
													"--4rxgx6": "rgb(51, 81, 162)",
												},
											},
										})}
										<RichText
											__fromCanvasComponent={true}
											className={"framer-15jv9q6"}
											data-framer-name={"View Now"}
											fonts={["GF;Instrument Sans-500"]}
											layoutDependency={layoutDependency}
											layoutId={"LfnT4TkRM"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											text={hC0hXqchb2}
											variants={{
												x6sYmpWDs: {
													"--extracted-r6o4lv": "rgb(51, 81, 162)",
												},
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
											{...addPropertyOverrides(
												{
													x6sYmpWDs: {
														children: (
															<React2.Fragment>
																<motion2.p
																	dir={"auto"}
																	style={{
																		"--font-selector":
																			"R0Y7SW5zdHJ1bWVudCBTYW5zLTYwMA==",
																		"--framer-font-family":
																			'"Instrument Sans", "Instrument Sans Placeholder", sans-serif',
																		"--framer-font-size": "12px",
																		"--framer-font-weight": "600",
																		"--framer-line-height": "18px",
																		"--framer-text-alignment": "center",
																		"--framer-text-color":
																			"var(--extracted-r6o4lv, rgb(51, 81, 162))",
																	}}
																>
																	{"Read More"}
																</motion2.p>
															</React2.Fragment>
														),
														fonts: ["GF;Instrument Sans-600"],
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<React2.Fragment>
												<motion2.p
													dir={"auto"}
													style={{
														"--font-selector":
															"R0Y7SW5zdHJ1bWVudCBTYW5zLTUwMA==",
														"--framer-font-family":
															'"Instrument Sans", "Instrument Sans Placeholder", sans-serif',
														"--framer-font-size": "12px",
														"--framer-font-weight": "500",
														"--framer-line-height": "18px",
														"--framer-text-alignment": "center",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-de74033a-6398-4597-880a-9ede5ecaf4fd, rgb(0, 0, 0)))",
													}}
												>
													{"Read More"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
									</motion2.a>
								</Link>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3BpKY.framer-1lp2ghf, .framer-3BpKY .framer-1lp2ghf { display: block; }",
	".framer-3BpKY.framer-1sl6m6s { align-content: center; align-items: center; cursor: default; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 200px; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 640px; }",
	".framer-3BpKY .framer-17svyrx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 200px; justify-content: center; overflow: visible; padding: 8px; position: relative; width: 240px; }",
	".framer-3BpKY .framer-1q3f2kt { flex: 1 0 0px; height: 1px; overflow: visible; position: relative; width: 100%; }",
	".framer-3BpKY .framer-qqbmyq { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: 200px; justify-content: space-around; overflow: visible; padding: 14px; position: relative; width: 400px; }",
	".framer-3BpKY .framer-12miagm { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-3BpKY .framer-usg3bo, .framer-3BpKY .framer-11gkuw8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 20px; justify-content: center; overflow: visible; padding: 0px 8px 0px 8px; position: relative; width: min-content; }",
	".framer-3BpKY .framer-138ewc6, .framer-3BpKY .framer-i7j81h, .framer-3BpKY .framer-1v1n44i, .framer-3BpKY .framer-15jv9q6 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-3BpKY .framer-11t541s { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: wrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-3BpKY .framer-woq4xh { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-3BpKY .framer-10k0v5p { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-3BpKY .framer-pk5f20 { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; min-height: 12px; min-width: 12px; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-3BpKY .framer-krhmgl { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-3BpKY .framer-jxsjis { flex: none; height: var(--framer-aspect-ratio-supported, 12px); position: relative; width: 12px; }",
	".framer-3BpKY.framer-v-1uu7ksv .framer-pk5f20 { min-height: 18px; min-width: 18px; }",
	".framer-3BpKY.framer-v-1uu7ksv .framer-jxsjis { height: var(--framer-aspect-ratio-supported, 18px); width: 18px; }",
	...css2,
	'.framer-3BpKY[data-border="true"]::after, .framer-3BpKY [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framerfnig4zHET = withCSS2(Component2, css3, "framer-3BpKY");
var stdin_default2 = Framerfnig4zHET;
Framerfnig4zHET.displayName = "Let's Talk Card";
Framerfnig4zHET.defaultProps = {
	height: 200,
	width: 640,
};
addPropertyControls2(Framerfnig4zHET, {
	variant: {
		options: ["awFU0mrem", "x6sYmpWDs"],
		optionTitles: ["Let's Talk Card", "Let's Talk Card - Hover"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	XUSUbL2ED: {
		__defaultAssetReference:
			"data:framer/asset-reference,rRjhAyKijqlXTxzw48Yh5U4LQ.png?originalFilename=ad1fe3840c8a8a3aa55d3c7fcf0e3c621e54e0b4.png&preferredSize=auto&width=2000&height=1333",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,rRjhAyKijqlXTxzw48Yh5U4LQ.png?originalFilename=ad1fe3840c8a8a3aa55d3c7fcf0e3c621e54e0b4.png&preferredSize=auto&width=2000&height=1333",
		},
		title: "Portrait Image",
		type: ControlType2.ResponsiveImage,
	},
	pPRfldf4V: {
		defaultValue: "Team Lead",
		displayTextArea: false,
		title: "Title",
		type: ControlType2.String,
	},
	GpVlhVAOO: {
		defaultValue: "Team Lead",
		displayTextArea: false,
		title: "Title 2",
		type: ControlType2.String,
	},
	btlkH0XLo: {
		defaultValue: "Desc",
		displayTextArea: false,
		title: "Desc",
		type: ControlType2.String,
	},
	CGQ6RMKTn: {
		defaultValue: "Project name",
		description: "",
		displayTextArea: false,
		title: "Project",
		type: ControlType2.String,
	},
	hC0hXqchb: {
		defaultValue: "Read More",
		displayTextArea: false,
		title: "Button Text",
		type: ControlType2.String,
	},
	oHdoMzddN: {
		title: "Link",
		type: ControlType2.Link,
	},
	Lm8fxgKJk: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType2.Boolean,
	},
});
addFonts(
	Framerfnig4zHET,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Instrument Sans",
					openType: true,
					source: "google",
					style: "normal",
					uiFamilyName: "Instrument Sans",
					url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSQb_gfwmS0v3_7Y.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Instrument Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Instrument Sans",
					url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npSTF-QfwmS0v3_7Y.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Instrument Sans",
					source: "google",
					style: "normal",
					uiFamilyName: "Instrument Sans",
					url: "https://fonts.gstatic.com/s/instrumentsans/v4/pximypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr-yp2JGEJOH9npST3-QfwmS0v3_7Y.woff2",
					weight: "500",
				},
			],
		},
		...ArrowRightFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:let-s-talk-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "awFU0mrem",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a388a4e8c1271596c25793932fb9581943efabb7f04a942d74fc0b8c62dc4850"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders LetSTalkCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"a388a4e8c1271596c25793932fb9581943efabb7f04a942d74fc0b8c62dc4850"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var let_s_talk_card_default = ComponentWithRoot;
export { let_s_talk_card_default as default };
